using System.Text;
using UnityEditor.Build.Content;

namespace Sample.SpecData.Editor.Generator
{
    internal sealed class GeneratorCS_SpecDataResourceLoader_Data : GeneratorCS
    {
        private GeneratorCS_SpecDataResourceLoader_Data(string ns, string encryptKey)
        {
            WriteLine("\r\n// <auto-generated>\r\n// Generator에서 만들어진 파일입니다. 수정하지 마세요.\r\n// </auto-generated>\r\n\r\n#pragma warning disable CS8669\r\n#pragma warning disable CS8625\r\n#pragma warning disable CS0436\r\n");
            WriteUsing("System.Linq");
            WriteUsing("System.Security.Cryptography");
            WriteUsing("System.Text");
            WriteUsing("UnityEngine");
            WriteNewLine();

            WriteNamespace(ns);
            WriteLine("[UnityEngine.Scripting.Preserve]");
            WriteClass("SpecDataResourceLoader", true, false);

            WriteLine("public static string LoadSpecData()");

            AutoClose();
        }

        public static void CreateCS(string folder, string ns, string encryptKey)
        {
            var dataFolder = string.Format("{0}/Data", folder);
            var generator = new GeneratorCS_SpecDataResourceLoader_Data(ns, encryptKey);
            generator.Save(dataFolder, "SpecDataResourceLoader_Data");
        }
    }
}
